# ChainFinity CI/CD Pipeline Configuration
# GitHub Actions Workflow Example

name: ChainFinity CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  TERRAFORM_VERSION: "1.6.6"
  KUBECTL_VERSION: "1.28.0"

jobs:
  validate-infrastructure:
    name: Validate Infrastructure Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format Check
        working-directory: infrastructure/terraform
        run: terraform fmt -recursive -check

      - name: Terraform Init
        working-directory: infrastructure/terraform
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: infrastructure/terraform
        run: terraform validate

      - name: Install yamllint
        run: pip install yamllint

      - name: Validate Kubernetes YAML
        working-directory: infrastructure/kubernetes
        run: |
          yamllint -c ../../.yamllint deployment.yaml
          yamllint -c ../../.yamllint backup/cronjob.yaml
          yamllint -c ../../.yamllint logging/elasticsearch.yaml
          yamllint -c ../../.yamllint monitoring/prometheus-config.yaml

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Validate Ansible Playbook
        working-directory: infrastructure/ansible
        run: ansible-lint playbook.yml || true

      - name: Kubectl Dry Run
        working-directory: infrastructure/kubernetes
        run: |
          kubectl apply --dry-run=client -f deployment.yaml
          kubectl apply --dry-run=client -f backup/cronjob.yaml

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    needs: validate-infrastructure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "infrastructure/"
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: validate-infrastructure
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        working-directory: infrastructure/terraform
        run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        working-directory: infrastructure/terraform
        run: terraform plan -var-file=terraform.tfvars.example -out=plan.out
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
